"""Shared experiment defaults, accounting, encoding, and prompt-template settings."""

import re
from pathlib import Path

ZERO_TOKENS = 0
INITIAL_COUNT = 0
COUNT_INCREMENT = 1
TEXT_ENCODING = "utf-8"
PROMPTS_DIRECTORY = Path(__file__).resolve().parent.parent.parent / "prompts"
SELF_REFINE_PROMPTS_DIRECTORY = PROMPTS_DIRECTORY / "self-refine"
AUDIT_PROMPTS_DIRECTORY = PROMPTS_DIRECTORY / "audit"
PROMPT_PLACEHOLDER = re.compile(r"\{\{(?P<name>\w+)\}\}")

OUTPUT_TOKENS_PER_BLOCK = 200_000
AUTO_COMPACT_WINDOW = 900_000
MAX_OUTPUT_TOKENS_PER_RESPONSE = 64_000
MAX_TURNS_PER_PHASE = 128
PROVIDER_MIN_TASK_BUDGET_TOKENS = 20_000
WARNING_TOKENS = 20_000
REASONING_EFFORT = "high"
MUSE_PREFIX = "muse-"
PROVIDER_TIMEOUT_SECONDS = 3_600
MILLISECONDS_PER_SECOND = 1_000
SDK_MAX_API_RETRIES = 0
INTERRUPTED_EXIT_CODE = 130
DEFAULT_MIN_ROUNDS = 10
DEFAULT_MIN_NO_GAP_CRITIQUES = 2
DEFAULT_MAX_CONCURRENCY = 1
DEFAULT_COMPUTE_MULTIPLIER_K = 1
DEFAULT_JUDGE_MODEL = "litellm/gpt-5.6-sol"
DEFAULT_AUDIT_MAX_TURNS = 64
MIN_COMPUTE_MULTIPLIER_K = 1
MAX_COMPUTE_MULTIPLIER_K = 8

RATE_LIMIT_EXIT_CODE = 75
RATE_LIMIT_RESET_PREFIX = "HARNESS_RATE_LIMIT_RESET="
SPEND_LIMIT_EXIT_CODE = 76

RECOVERY_MAX_RETRIES = 6
RECOVERY_BASE_DELAY_SECONDS = 2.0
RECOVERY_MAX_DELAY_SECONDS = 30.0
RECOVERY_BACKOFF_MULTIPLIER = 2
