"""Refinement settings, verdicts, and prompt-file locations."""

from harness.utils.constants import SELF_REFINE_PROMPTS_DIRECTORY

LAST_LINE_INDEX = -1

NO_GAPS_VERDICT = "VERDICT: NO_GAPS"
GAPS_FOUND_VERDICT = "VERDICT: GAPS_FOUND"

SOLVE_PROMPT_FILE = SELF_REFINE_PROMPTS_DIRECTORY / "solve.md"
CRITIQUE_PROMPT_FILE = SELF_REFINE_PROMPTS_DIRECTORY / "critique.md"
REVISE_PROMPT_FILE = SELF_REFINE_PROMPTS_DIRECTORY / "revise.md"
WARNING_PROMPT_FILE = SELF_REFINE_PROMPTS_DIRECTORY / "warning.md"
